[package]
name = "rust-hexagonal-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-rt = "2.8.0"
diesel = { version = "2.1.0", features = ["postgres", "r2d2"] }
deadpool-diesel = "0.4.1"
dotenvy = "0.15"
once_cell = "1.18.0"
chrono = "0.4.26"