version: '3.9'
services:
  postgres-db:
    image: postgres:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env 
    networks:
      - HEEPOKE

networks:
  HEEPOKE: